### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/share/passenger/helper-scripts/tmp/' [SOLVED]

### ISSUE THREAD

**Issue by furibund** [totaljs/emptyproject#1]
Using total.js on webspace with Phusion Passenger / Apache produces following
[REDACTED]
``` 
Error: EACCES: permission denied, mkdir '/usr/share/passenger/helper-scripts/tmp/' Error: EACCES: permission denied, mkdir '/usr/share/passenger/helper-scripts/tmp/'
  at Object.mkdirSync (fs.js:753:3)
    at FrameworkPath.verify (${APP_DIR}/node_modules/total.js/index.js:9739:25)
    at FrameworkPath.temp (${APP_DIR}/node_modules/total.js/index.js:9837:7)
    at FrameworkCache.loadpersistent (${APP_DIR}/node_modules/total.js/index.js:9973:21)
    at FrameworkCache.init (${APP_DIR}/node_modules/total.js/index.js:9931:8)
    at ${APP_DIR}/node_modules/total.js/index.js:6750:11
    at Framework.F.$bundle (${APP_DIR}/node_modules/total.js/index.js:3699:2)
    at Framework.F.initialize (${APP_DIR}/node_modules/total.js/index.js:6743:4)
    at ${APP_DIR}/node_modules/total.js/index.js:7006:5
    at Framework.F.$startup (${APP_DIR}/node_modules/total.js/index.js:3927:10)
```
What can I do without having root access?

**Comment by petersirka** [comment]
Hi. Try to follow these instructions:
<https://docs.totaljs.com/latest/en.html#pages~Troubleshooting~(how-to-run-total-js-app-on-passenger-web-server-)>

**Comment by furibund** [comment]
Thx for the fast answer 👍 - I'll try it this evening.

**Comment by furibund** [comment]
That's it! :)
Maybe you put the error message on the troubleshooting page.
I googled a dozen times without finding your page before I opened this issue.
